NWChem: The exchange-correlation code
The exchange-correlation code
The Gaussian DFT module
Files
file grid_pscreen.F
Screen the grid points.
file dft_utilmap.F
Various routines that build or use mappings between atoms, matrix elements and what not.
file xc_eval_basis.F
Evaluate basis functions and derivatives.
file xc_rhogen.F
Evaluate density and derivatives.
subroutine setacmat (delrho, Amat, Cmat, qwght, ipol, nq, GRAD, xform_Cmat, kske, Mmat)
Do clever stuff to the partial derivatives.
subroutine transform_cmat (delrho, Cmat, ipol, nq)
subroutine ts_eval_fnl (rho, delrho, Amat, Amat2, Cmat, Cmat2, nq, Ts, qwght, grad, ldew, func, do_2nd, ttau, kske, Mmat, Mmat2, do_3rd, Amat3, Cmat3, ldew2)
the functional evaluation routine
subroutine xc_eval_fnl (rho, delrho, Amat, Amat2, Cmat, Cmat2, nq, Ex, Ec, qwght, grad, ldew, func, do_2nd, ttau, kske, Mmat, Mmat2, StericEnergy, do_3rd, Amat3, Cmat3, ldew2)
the functional evaluation routine
subroutine xc_eval_fnl_fde (rho, delrho, Amat, Amat2, Cmat, Cmat2, nq, Ex, Ec, qwght, grad, ldew, func, do_2nd, ttau, kske, Mmat, Mmat2, StericEnergy, do_3rd, Amat3, Cmat3, ldew2)
subroutine calc_rgamma (ipol, nq, delrho, rgamma)
subroutine xc_rhogen (what_in, tol_rho, basis, g_dens, max_at_bf, natoms, curatoms, ncuratoms, npert, ipol, nq, nbf, mbf, GRAD, ipol2, F, Pmat, ff, ffd, chi, delchi, heschi, ibf, iniz, ifin, rho, delrho, lap, rchi_atom, rdelchi_atom, rdens_atom, cetobfr, wmax, ttau, kske, dolap)
Evaluate the density and their derivatives on a grid.
subroutine xc_drhonuc (nq, ipol, n0, n1, delrho, heschi, delchi, ff, ffd, ii, iat)
subroutine xc_dchiff (nq, n0, n1, delrho, delchi, ff)
subroutine xc_dchiffp (nq, ipol2, n0, n1, rho, delchi, ff, ii, iat)
integer function xc_rhoscreen (grad, ipol, natoms, npert, iniz, tol_rho, wmax, nz, rchi_atom, rdelchi_atom, rdens_atom)
subroutine xc_getdmblock (nz, nonz0, natoms, cetobfr, g_dens, Pmat, nbhandl)
subroutine xc_dmget (repdm, nbf_ld, ilo, ihi, jlo, jhi, Pmat, nbfia)
subroutine td_rhogen (what, tol_rho, basis, g_dens, max_at_bf, natoms, curatoms, ncuratoms, npert, ipol, nq, nbf, mbf, GRAD, ipol2, F, Pmat, ff, ffd, chi, delchi, heschi, ibf, iniz, ifin, rho, delrho, lap, rchi_atom, rdelchi_atom, rdens_atom, cetobfr, wmax, ttau, kske, dolap)
subroutine xc_tabcd (what, l3d_dum, tol_rho, Tmat, TTmat, Amat, Bmat, Cmat, Dmat, Emat, Fmat, qxyz, xyz, chi, delchi, heschi, curatoms, ncuratoms, nmat, ipol, nq, nbf, max_at_bf, max_at_bf2, GRAD, basis, natoms, iniz, ifin, g_vxc, ibf, rchi_atom, rdelchi_atom, rdens_atom, cetobfr, kske, Mmat, scr)
Evaluate various matrix elements over the functionals.
subroutine upd_atombl_nb (g_array, basis, iat, jat, buf, nbhandle)
Detailed Description
Function Documentation
calc_rgamma()
subroutine calc_rgamma (integer ipol, integer nq, double precision, dimension(nq,3,ipol) delrho, double precision, dimension(nq,3) rgamma)
Parameters
ipol [Input] The number of spin channels
nq [Input] The number of grid points
delrho [Input] The density gradient
rgamma [Output] The density gradien! t norm
Referenced by xc_eval_fnl().
setacmat()
subroutine setacmat (double precision, dimension(nq,3,ipol) delrho, double precision, dimension(nq,ipol) Amat, double precision, dimension(nq,3,ipol) Cmat, double precision, dimension(nq) qwght, integer ipol, integer nq, logical GRAD, logical xform_Cmat, logical kske, double precision, dimension(nq,ipol) Mmat)
Do clever stuff to the partial derivatives.
The density functionals return plain partial derivatives of the of the functionals in addition to the energy. This routine modifies those quantities to get them in a form that is more "convenient" in the construction of various matrices.
In all cases this modification includes multiplying the partial derivatives for each grid point with the corresponding quadrature weight.
If xform_Cmat is set to .TRUE. then the 1st derivatives with respect to the norm of the electron density gradient are replaced in the closed shell case with
\begin{eqnarray*} Cmat(i,1,1) &=& \frac{\partial\rho(r)}{\partial x} \left(\frac{\partial f}{\partial\gamma^{\alpha\alpha}} + \frac{1}{2}\frac{\partial f}{\partial\gamma^{\alpha\beta}} \right) w_i\\\ Cmat(i,2,1) &=& \frac{\partial\rho(r)}{\partial y} \left(\frac{\partial f}{\partial\gamma^{\alpha\alpha}} + \frac{1}{2}\frac{\partial f}{\partial\gamma^{\alpha\beta}} \right) w_i\\\ Cmat(i,3,1) &=& \frac{\partial\rho(r)}{\partial z} \left(\frac{\partial f}{\partial\gamma^{\alpha\alpha}} + \frac{1}{2}\frac{\partial f}{\partial\gamma^{\alpha\beta}} \right) w_i\\\ \end{eqnarray*}
and in the open shell case with
\begin{eqnarray*} Cmat(i,1,1) &=& \left(2\frac{\partial\rho^\alpha(r)}{\partial x} \frac{\partial f}{\partial\gamma^{\alpha\alpha}} + \frac{\partial\rho^\beta(r)}{\partial x} \frac{\partial f}{\partial\gamma^{\alpha\beta}}\right)w_i \\\ Cmat(i,2,1) &=& \left(2\frac{\partial\rho^\alpha(r)}{\partial y} \frac{\partial f}{\partial\gamma^{\alpha\alpha}} + \frac{\partial\rho^\beta(r)}{\partial y} \frac{\partial f}{\partial\gamma^{\alpha\beta}}\right)w_i \\\ Cmat(i,3,1) &=& \left(2\frac{\partial\rho^\alpha(r)}{\partial z} \frac{\partial f}{\partial\gamma^{\alpha\alpha}} + \frac{\partial\rho^\beta(r)}{\partial z} \frac{\partial f}{\partial\gamma^{\alpha\beta}}\right)w_i \\\ Cmat(i,1,2) &=& \left(2\frac{\partial\rho^\beta(r)}{\partial x} \frac{\partial f}{\partial\gamma^{\beta\beta}} + \frac{\partial\rho^\alpha(r)}{\partial x} \frac{\partial f}{\partial\gamma^{\alpha\beta}}\right)w_i \\\ Cmat(i,2,2) &=& \left(2\frac{\partial\rho^\beta(r)}{\partial y} \frac{\partial f}{\partial\gamma^{\beta\beta}} + \frac{\partial\rho^\alpha(r)}{\partial y} \frac{\partial f}{\partial\gamma^{\alpha\beta}}\right)w_i \\\ Cmat(i,3,2) &=& \left(2\frac{\partial\rho^\beta(r)}{\partial z} \frac{\partial f}{\partial\gamma^{\beta\beta}} + \frac{\partial\rho^\alpha(r)}{\partial z} \frac{\partial f}{\partial\gamma^{\alpha\beta}}\right)w_i \\\ \end{eqnarray*}
The grid point is indexed with i, the density functional is referred to with \(f\), and \(w\) is the quadrature weight.
Parameters
ipol [Input] The number of spin channels
nq [Input] The number of grid points
grad [Input] If .TRUE. the density functional is a GGA
xform_cmat [Input] If .TRUE. do the elaborate transformation
delrho [Input] The gradient of the density
amat [In/Output] \(\partial f/\parti! al\rho^\sigma\)
cmat [In/Output] \(\partial f/\par! tial\gamma^{\sigma\sigma'}\)
mmat [In/Output] \(\partial f/\parti! al\tau^\sigma\)
kske [Input] If .TRUE. the density functional is a meta-GGA
qwght [Input] The quadrature weights
References transform_cmat().
Referenced by ts_eval_fnl(), and xc_eval_fnl().
td_rhogen()
subroutine td_rhogen (integer what, double precision tol_rho, integer basis, integer, dimension(*) g_dens, integer max_at_bf, integer natoms, integer, dimension(*) curatoms, integer ncuratoms, integer npert, integer ipol, integer nq, integer nbf, integer mbf, logical GRAD, integer ipol2, double precision, dimension(max_at_bf*max_at_bf) F, double precision, dimension(*) Pmat, double precision, dimension(nq,*) ff, double precision, dimension(nq,3,*) ffd, double precision, dimension(nq,mbf) chi, double precision, dimension(nq,3,mbf) delchi, double precision, dimension(nq,6,mbf) heschi, integer, dimension(mbf) ibf, integer, dimension(natoms) iniz, integer, dimension(natoms) ifin, double precision, dimension(nq,ipol2,*) rho, double precision, dimension(nq,3,ipol,*) delrho, double precision, dimension(nq,ipol2,*) lap, double precision, dimension(natoms) rchi_atom, double precision, dimension(natoms) rdelchi_atom, double precision, dimension(natoms,natoms,ipol) rdens_atom, integer, dimension(2,natoms) cetobfr, double precision wmax, double precision, dimension(nq,ipol,*) ttau, logical kske, logical dolap)
Parameters
grad [Input] .true. when using gradient corrected functional
kske [Input] .true. when using kinetic energy density functional
what [Input] What to calculate
what=0: calculate density
what=1: calculate perturbed density (derivative with respect to electron position)
what=2: calculate derivative with respect to nuclear coordinates
basis [Input] basis set handle
ipol [Input] no. of spin channels
ipol2 [Input] no. of spin channels in density
1 if closed shell
3 if open shell
nbf [Input] no. of basis functions
mbf [Input] "restricted" no. of basis function! s
max_at_bf [Input] max no. bf per atom
nq [Input] no. of quadrature points
natoms [Input] no. of atoms
wmax [Input] max weight
npert [Input] number of perturbed densities
curatoms [Input] indexing array for "active" atoms
ncuratoms [Input] number of currently active ato! ms
g_dens [Input] GA handle for DM
ibf [Input] mapping of nbf_ao -> mbf
iniz [Input] mapping of nbf_ao -> mbf
ifin [Input] mapping of nbf_ao -> mbf
tol_rho [Input] accuracy for rho evaluation
chi [Input] function values
delchi [Input] function gradients
heschi [Input] function hessians
ttau [Output] Total Kohn-Sham K.E.d! ensity
delrho [Output] Derivative of den! sity
pmat [Scratch] scratch vector
f [Scratch] scratch vecto! r
ff [Scratch] scratch array
ffd [Scratch] scratch array
rho [Output] The density
rchi_atom [Input] Screening parameters
rdelchi_atom [Input] Screening paramet! ers
rdens_atom [Input] Screeni! ng parameters
cetobfr [Input] Centers to basis functions
transform_cmat()
subroutine transform_cmat (double precision, dimension(nq,3,ipol) delrho, double precision, dimension(nq,3,ipol) Cmat, integer ipol, integer nq)
Referenced by dftg_gridv0b(), and setacmat().
ts_eval_fnl()
subroutine ts_eval_fnl (double precision, dimension(*) rho, double precision, dimension(*) delrho, double precision, dimension(*) Amat, double precision, dimension(*) Amat2, double precision, dimension(*) Cmat, double precision, dimension(*) Cmat2, integer nq, double precision Ts, double precision, dimension(nq) qwght, logical grad, logical ldew, double precision, dimension(nq) func, logical do_2nd, double precision, dimension(*) ttau, logical kske, double precision, dimension(*) Mmat, double precision, dimension(*) Mmat2, logical do_3rd, double precision, dimension(*) Amat3, double precision, dimension(*) Cmat3, logical ldew2)
the functional evaluation routine
This routine iterates over the components of the current density functional and evaluates and accumulates all density dependent terms. At present it will evaluate
the kinetic energy energy
the kinetic energy 1st order partial derivatives wrt density
as desired.
Parameters
rho [Input] The electron density \(\rho^\alpha\) and \(\rho^\beta\).
delrho [Input] The electron density gradient \(\partial\rho^\alpha/\partial r\) and \(\partial\rho^\beta/\partial r\)
ttau [Input] The kinetic energy density
ts [Output] The exchange energy
References setacmat(), ts_tf(), and ts_vw().
Referenced by grid_quadv0b().
upd_atombl_nb()
subroutine upd_atombl_nb (integer g_array, integer basis, integer iat, integer jat, double precision, dimension(*) buf, integer nbhandle)
Referenced by xc_tabcd(), zora_tabcd(), and zora_tabcd_efg().
xc_dchiff()
subroutine xc_dchiff (integer nq, integer n0, integer n1, double precision, dimension(nq,3) delrho, double precision, dimension(nq,3,*) delchi, double precision, dimension(nq,*) ff)
Referenced by xc_drhonuc(), and xc_rhogen().
xc_dchiffp()
subroutine xc_dchiffp (integer nq, integer ipol2, integer n0, integer n1, double precision, dimension(nq,ipol2,3,*) rho, double precision, dimension(nq,3,*) delchi, double precision, dimension(nq,*) ff, integer ii, integer iat)
Referenced by xc_drhonuc(), and xc_rhogen().
xc_dmget()
subroutine xc_dmget (double precision, dimension(*) repdm, integer nbf_ld, integer ilo, integer ihi, integer jlo, integer jhi, double precision, dimension(nbfia,*) Pmat, integer nbfia)
Referenced by xc_rhogen().
xc_drhonuc()
subroutine xc_drhonuc (integer nq, integer ipol, integer n0, integer n1, double precision, dimension(nq,3,ipol,3,*) delrho, double precision, dimension(nq,6,*) heschi, double precision, dimension(nq,3,*) delchi, double precision, dimension(nq,*) ff, double precision, dimension(nq,3,*) ffd, integer ii, integer iat)
References xc_dchiff(), and xc_dchiffp().
Referenced by xc_rhogen().
xc_eval_fnl()
subroutine xc_eval_fnl (double precision, dimension(*) rho, double precision, dimension(*) delrho, double precision, dimension(*) Amat, double precision, dimension(*) Amat2, double precision, dimension(*) Cmat, double precision, dimension(*) Cmat2, integer nq, double precision Ex, double precision Ec, double precision, dimension(nq) qwght, logical grad, logical ldew, double precision, dimension(nq) func, logical do_2nd, double precision, dimension(*) ttau, logical kske, double precision, dimension(*) Mmat, double precision, dimension(*) Mmat2, double precision StericEnergy, logical do_3rd, double precision, dimension(*) Amat3, double precision, dimension(*) Cmat3, logical ldew2)
the functional evaluation routine
This routine iterates over the components of the current density functional and evaluates and accumulates all density dependent terms. At present it will evaluate
the exchange-correlation energy
the exchange-correlation 1st order partial derivatives
the exchange-correlation 2nd order partial derivatives
as desired.
Parameters
rho [Input] The electron density \(\rho^\alpha\) and \(\rho^\beta\).
delrho [Input] The electron density gradient \(\partial\rho^\alpha/\partial r\) and \(\partial\rho^\beta/\partial r\)
ttau [Input] The kinetic energy density
ex [Output] The exchange energy
ec [Output] The correlation energy
References calc_rgamma(), setacmat(), steric_energy(), xc_bc95(), xc_bc95_d2(), xc_becke88(), xc_bnl(), xc_camb88(), xc_cams12x(), xc_camxlsd(), xc_camxpbe96(), xc_cdldf(), xc_cdldf_d2(), xc_cm05(), xc_cm05_d2(), xc_cm06(), xc_cm06_d2(), xc_cm11(), xc_cm11_d2(), xc_cpbe96(), xc_cpkzb99(), xc_cpkzb99_d2(), xc_cs00(), xc_csogga(), xc_csogga_d2(), xc_ctpss03(), xc_ctpss03_d2(), xc_cvs98(), xc_cvs98_d2(), xc_dirac(), xc_ft97(), xc_gill96(), xc_hcth(), xc_hcth_d2(), xc_kt1(), xc_lb94(), xc_lyp88(), xc_op(), xc_optc(), xc_optx(), xc_p81(), xc_perdew86(), xc_perdew91(), xc_pw91lda(), xc_s12x(), xc_spbe96(), xc_ssbd_1(), xc_xb86b(), xc_xdldf(), xc_xdldf_d2(), xc_xm05(), xc_xm05_d2(), xc_xm06(), xc_xm06_d2(), xc_xm11(), xc_xm11_d2(), xc_xmpw91(), xc_xmvs15(), xc_xmvs15_d2(), xc_xpbe96(), xc_xpkzb99(), xc_xpkzb99_d2(), xc_xpw6(), xc_xpw86(), xc_xpw91(), xc_xsogga(), xc_xsogga_d2(), xc_xtpss03(), xc_xtpss03_d2(), xc_xvs98(), xc_xvs98_d2(), and xc_xwpbe().
Referenced by dftg_gridv0b(), and grid_quadv0b().
xc_eval_fnl_fde()
subroutine xc_eval_fnl_fde (double precision, dimension(*) rho, double precision, dimension(*) delrho, double precision, dimension(*) Amat, double precision, dimension(*) Amat2, double precision, dimension(*) Cmat, double precision, dimension(*) Cmat2, integer nq, double precision Ex, double precision Ec, double precision, dimension(nq) qwght, logical grad, logical ldew, double precision, dimension(nq) func, logical do_2nd, double precision, dimension(*) ttau, logical kske, double precision, dimension(*) Mmat, double precision, dimension(*) Mmat2, double precision StericEnergy, logical do_3rd, double precision, dimension(*) Amat3, double precision, dimension(*) Cmat3, logical ldew2)
Parameters
rho [Input] The electron density \(\rho^\alpha\) and \(\rho^\beta\).
delrho [Input] The electron density gradien! t \(\partial\rho^\alpha/\partial r\) and \(\partial\rho^\beta/\partial r\)
ttau [Input] The kinetic energy density
ex [Output] The exchange energy
ec [Output] The correlation energy
Referenced by grid_quadv0b().
xc_getdmblock()
subroutine xc_getdmblock (integer, dimension(*) nz, integer nonz0, integer natoms, integer, dimension(2,*) cetobfr, integer g_dens, double precision, dimension(*) Pmat, integer nbhandl)
Referenced by xc_rhogen().
xc_rhogen()
subroutine xc_rhogen (integer what_in, double precision tol_rho, integer basis, integer, dimension(*) g_dens, integer max_at_bf, integer natoms, integer, dimension(*) curatoms, integer ncuratoms, integer npert, integer ipol, integer nq, integer nbf, integer mbf, logical GRAD, integer ipol2, double precision, dimension(max_at_bf*max_at_bf) F, double precision, dimension(*) Pmat, double precision, dimension(nq,*) ff, double precision, dimension(nq,3,*) ffd, double precision, dimension(nq,mbf) chi, double precision, dimension(nq,3,mbf) delchi, double precision, dimension(nq,6,mbf) heschi, integer, dimension(mbf) ibf, integer, dimension(natoms) iniz, integer, dimension(natoms) ifin, double precision, dimension(nq,ipol2,*) rho, double precision, dimension(nq,3,ipol,*) delrho, double precision, dimension(nq,ipol2,*) lap, double precision, dimension(natoms) rchi_atom, double precision, dimension(natoms) rdelchi_atom, double precision, dimension(natoms,natoms,ipol) rdens_atom, integer, dimension(2,natoms) cetobfr, double precision wmax, double precision, dimension(nq,ipol,*) ttau, logical kske, logical dolap)
Evaluate the density and their derivatives on a grid.
Parameters
grad [Input] .true. when using gradient corrected functional
kske [Input] .true. when using kinetic energy density functional
what_in [Input] What to calculate
what=0: calculate density
what=1: calculate perturbed density (derivative with respect to electron position)
what=2: calculate derivative with respect to nuclear coordinates
dolap [Input] .true. if the Laplacian of the density is required
basis [Input] basis set handle
ipol [Input] no. of spin channels
ipol2 [Input] no. of spin channels in density
1 if closed shell
3 if open shell
nbf [Input] no. of basis functions
mbf [Input] "restricted" no. of basis functions
max_at_bf [Input] max no. bf per atom
nq [Input] no. of quadrature points
natoms [Input] no. of atoms
wmax [Input] max weight
npert [Input] number of perturbed densities
curatoms [Input] indexing array for "active" atoms
ncuratoms [Input] number of currently active atoms
g_dens [Input] GA handle for DM
ibf [Input] mapping of nbf_ao -> mbf
iniz [Input] mapping of nbf_ao -> mbf
ifin [Input] mapping of nbf_ao -> mbf
tol_rho [Input] accuracy for rho evaluation
chi [Input] function values
delchi [Input] function gradients
heschi [Input] function hessians
ttau [Output] Total Kohn-Sham K.E.density
delrho [Output] Derivative of density
pmat [Scratch] scratch vector
f [Scratch] scratch vector
ff [Scratch] scratch array
ffd [Scratch] scratch array
rho [Output] The density
rchi_atom [Input] Screening parameters
rdelchi_atom [Input] Screening parameters
rdens_atom [Input] Screening parameters
cetobfr [Input] Centers to basis functions
References gat_mat(), xc_dchiff(), xc_dchiffp(), xc_dmget(), xc_drhonuc(), xc_getdmblock(), and xc_rhoscreen().
Referenced by dftg_gridv0b(), grid_quadv0b(), and grid_sicrho().
xc_rhoscreen()
integer function xc_rhoscreen (logical grad, integer ipol, integer natoms, integer npert, integer, dimension(natoms) iniz, double precision tol_rho, double precision wmax, integer, dimension(*) nz, double precision, dimension(*) rchi_atom, double precision, dimension(*) rdelchi_atom, double precision, dimension(natoms,natoms,ipol) rdens_atom)
Referenced by xc_rhogen().
xc_tabcd()
subroutine xc_tabcd (integer what, logical l3d_dum, double precision tol_rho, double precision, dimension(*) Tmat, double precision, dimension(*) TTmat, double precision, dimension(nq,ipol,*) Amat, double precision, dimension(nq,max_at_bf) Bmat, double precision, dimension(nq,3,ipol,*) Cmat, double precision, dimension(nq,3,max_at_bf) Dmat, double precision, dimension(nq,max_at_bf) Emat, double precision, dimension(nq,3,max_at_bf) Fmat, double precision, dimension(3,*) qxyz, double precision, dimension(3,*) xyz, double precision, dimension(nq,nbf) chi, double precision, dimension(nq,3,nbf) delchi, double precision, dimension(nq,6,*) heschi, integer, dimension(*) curatoms, integer ncuratoms, integer nmat, integer ipol, integer nq, integer nbf, integer max_at_bf, integer max_at_bf2, logical GRAD, integer basis, integer natoms, integer, dimension(natoms) iniz, integer, dimension(natoms) ifin, integer, dimension(*) g_vxc, integer, dimension(nbf) ibf, double precision, dimension(natoms) rchi_atom, double precision, dimension(natoms) rdelchi_atom, double precision, dimension(natoms,natoms,ipol) rdens_atom, integer, dimension(2,natoms) cetobfr, logical kske, double precision, dimension(nq,ipol,*) Mmat, double precision, dimension(nq) scr)
Evaluate various matrix elements over the functionals.
This routine evaluates a variety of matrix elements that involve the density functional.
Note that there are some inconsistencies with respect to the kinetic energy density. NWChem defines the kinetic energy density as
\begin{eqnarray*} \tau_1 &=& \sum_i \frac{1}{2}\langle\phi_i|\nabla^2|\phi_i\rangle \end{eqnarray*}
In most density functionals the kinetic energy density is defined as
\begin{eqnarray*} \tau_2 &=& \sum_i \langle\phi_i|\nabla^2|\phi_i\rangle \end{eqnarray*}
the reason being that the factor 1/2 can easily be absorpted into the density functional parameters. As a result the density functional routines evaluate
\begin{eqnarray*} e &=& f(\rho,\gamma,\tau_2) \\\ Amat = &=& \frac{\partial f(\rho,\gamma,\tau_2)}{\partial\rho} \\\ Cmat = &=& \frac{\partial f(\rho,\gamma,\tau_2)}{\partial\gamma} \\\ Mmat = &=& \frac{\partial f(\rho,\gamma,\tau_2)}{\partial\tau_2} \\\ \end{eqnarray*}
The NWDFT module in NWChem handles this situation by conceptually wrapping the functional routines used (the actual implementation just scales \(\tau\) by a factor 2)
\begin{eqnarray*} e &=& g(\rho,\gamma,\tau_1) \\\ g(\rho,\gamma,\tau_1) &=& f(\rho,\gamma,2\tau_1) \\\ \end{eqnarray*}
As a result, however, the density functional routines now return
\begin{eqnarray*} e &=& g(\rho,\gamma,\tau_1) \\\ Amat = &=& \frac{\partial g(\rho,\gamma,\tau_1)}{\partial\rho} \\\ Cmat = &=& \frac{\partial g(\rho,\gamma,\tau_1)}{\partial\gamma} \\\ Mmat = &=& \frac{\partial g(\rho,\gamma,\tau_1)}{\partial\tau_2} \\\ \end{eqnarray*}
where there is an inconsistency in the derivative wrt. to \(\tau\) as \(g\) is a function of \(\tau_1\) but differentiated wrt. \(\tau_2\).
In the NWXC module the differentation techniques deployed do not allow such inconsistencies and \(g\) is strictly differentiated wrt. \(\tau_1\). This results in a factor \(2\) difference that we need to compensate for.
Parameters
grad [Input] .True. if functional depends on density gradient
what [Input] What should be calculated:
what=0: Do everything (?)
what=1: CPKS_LHS
what=2: CPKS_RHS
what=3: NMR_RHS
basis [Input] The basis set handle
max_at_bf [Input] The maximum number of basis functions on an atom
max_at_bf2 [Input] The maximum number of basis functions on an atom
nmat [Input] Number of XC matrices (alpha + beta sets) to compute, e.g. the number of perturbations for CPSCF.
ipol [Input] The number of spin channels
nq [Input] The number of grid points
nbf [Input] The number of basis functions
natoms [Input] The number of atoms
ncuratoms [Input] The number of current "active" atoms
curatoms [Input] Mapping array for current atoms
tol_rho [Input] The electron density threshold
g_vxc [Input] The GA handle for Fock matrix derivatives
tmat [Scratch]
ttmat [Scratch]
rchi_atom [Input] The maximum basis function radius for each atom in this call
rdelchi_atom [Input] The maximum radius of the basis function gradient for each atom in this call
rdens_atom Not used
cetobfr [Input] Mapping from center to basis functions (how different from iniz and ifin?):
cetobfr(1,*): first basis function
cetobfr(2,*): last basis function
l3d_dum [Junk]
amat [Input] The derivative wrt rho
cmat [Input] The derivative wrt rgamma
mmat [Input] The derivative wrt tau
emat [Scratch] NMR only
fmat [Scratch] NMR only
qxyz [Input] Grid point coordinates
xyz [Input] Nuclear coordinates
kske [Input] .True. if functional depends on kinetic energy density
bmat [Scratch]
dmat [Scratch]
iniz [Input] The first basis function for each atom
ifin [Input] The last basis function for each atom
chi [Input] The value of the basis functions at the grid points
delchi [Input] The value of the gradient of the basis functions at the grid points
heschi [Input] The value of the Hessian of the basis functions at the grid points
ibf [Input] The rank of the basis function for every basis function (why do we need this?)
scr [Scratch] Temporary stuff in quadrature
References scat_mat(), scat_mat3(), scat_matup(), transp_mat(), transp_mat3(), upd_atombl_nb(), xc_atom_block(), and xc_atom_blockd().
Referenced by dftg_gridv0b(), and grid_quadv0b().